### ISSUE TITLE
Bowels

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#107]

**Comment by sarawilcox** [comment]
We don't use 'bowel movement', we use 'poo'. But in colonoscopy, for example, our user research shows that people understand 'bowels' as in 'empty your bowels'. 
We'd like to test this further.

**Comment by sarawilcox** [comment]
Comments from NHS.UK Slack:
We have gone with "small intestine" in one small line in the stomach cancer content. 

Maybe "bowel" is large intestine + colon + rectum? and we just avoid "large bowel"?

"large colon" also a possibility...

Google Trends suggests large intestine is having something of a renaissance after declining earlier this year (https://files.slack.com/files-pri/T0FRZQSMB-FPDMADJ1Z/image.png)

On the colonoscopy page we just said bowels rather than specifying large intestine or large bowel eg, “it’s a test to “check inside your bowels” and said it’s looking for the cause of your bowel symptoms” or “signs of bowel conditions”. When tested users understood the content.

**Comment by sarahallen57** [comment]
I'm questioning whether you can say "large colon" as there is only one colon, not a large and small. 
The colon is very different in function, shape and size to the small intestine. 
I don't think colonoscopies usually examine much (if any) or the small intestine, as it's just not physically possible to go very far beyond the ilium (I think you need a gastroscopy to access the duodenum and beyond, from what I understand). 
The terms "large bowel (colon)" and "small bowl (small intestines)" is used by Cancer Research UK (https://www.cancerresearchuk.org/about-cancer/cancer-in-general/tests/colonoscopy and https://www.cancerresearchuk.org/about-cancer/small-bowel-cancer/about). Images really help when it comes to bowels, as the words large and small, although that's their common names, are misleading and perhaps don't mean anything to people?

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see how much interest there is in this issue now. Can we close it?

**Comment by EllenDoyle** [comment]
Many people, especially the older generation, use the word bowel rather than other terminology. As bowel conditions occur more frequently in older people, would it be appropriate to do some UR with this population?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
