### ISSUE TITLE
Mucus, phlegm and sputum

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#112]
The medicines team is using and testing "mucus (phlegm)".

**Comment by OliviaThornton** [comment]
An extract of search terms provided by Shaun Hasney has shown that so far this year (as of mid-Feb), there have been:

- 701 searches for **Phlegm** 
- 46 searches for **Flem**
- 286 searches for **mucus** 
- 9 searches for **sputum**

**Comment by OliviaThornton** [comment]
Definitions: 

Phlegm:

> "the thick viscous substance secreted by the mucous membranes of the respiratory passages, especially when produced in excessive quantities during a cold."

Flem: 

> Not available


Mucus: 

> "a slimy substance, typically not miscible with water, secreted by the mucous membranes and glands of animals for lubrication, protection, etc."

Sputum:

> "a mixture of saliva and mucus coughed up from the respiratory tract, typically as a result of infection or other disease and often examined microscopically to aid medical diagnosis."

**Comment by sarawilcox** [comment]
Google trends show this

![Screenshot 2021-03-05 at 17 01 11](https://user-images.githubusercontent.com/45792959/110148227-7b4b4000-7dd4-11eb-87e5-d9391adc93c4.png)

**Comment by sarawilcox** [comment]
This is what search results on the NHS website show.

![Screenshot 2021-03-05 at 17 03 13](https://user-images.githubusercontent.com/45792959/110148444-b9486400-7dd4-11eb-8da2-8c419cc61899.png)
![Screenshot 2021-03-05 at 17 03 07](https://user-images.githubusercontent.com/45792959/110148459-be0d1800-7dd4-11eb-90d4-0a120c941f2e.png)

**Comment by OliviaThornton** [comment]
![Screenshot 2021-03-08 at 09 21 11](https://user-images.githubusercontent.com/72209280/110301135-a2ca2480-7fef-11eb-9e66-a1196878b219.png)
![Screenshot 2021-03-08 at 09 22 00](https://user-images.githubusercontent.com/72209280/110301235-becdc600-7fef-11eb-93ec-7cc119771b78.png)
![Screenshot 2021-03-08 at 09 25 07](https://user-images.githubusercontent.com/72209280/110301607-2edc4c00-7ff0-11eb-939e-ae8880b28702.png)
![Screenshot 2021-03-08 at 09 26 19](https://user-images.githubusercontent.com/72209280/110301748-5a5f3680-7ff0-11eb-8a35-f73af9bf0093.png)

**Comment by sarawilcox** [comment]
I've put out a call on NHS.UK Slack #content channel for more UR. Is this still an issue?

**Comment by sarawilcox** [comment]
No one has shown and interest in this issue on the NHS.UK or public Slack channel. I'm closing it for now.
