### ISSUE TITLE
Next of kin

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#165]
We're using this in the new forms guidance and we use it on this page: https://www.nhs.uk/using-the-nhs/nhs-services/hospitals/staying-in-hospital-as-an-inpatient/. Do people understand the phrase? Or is it better to say "your closest relative or friend"? Is that accurate?

**Comment by NettyKo** [comment]
I think people do understand, although it's not obvious for those whose English isn't their first language. I'm not sure "your closest relative or friend" is accurate as this is usually a person nominated by the patients, but not necessarily closest to them.

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
