### ISSUE TITLE
Weights and measures, e.g. kg, lb, oz

### ISSUE THREAD

**Issue by Chloephilippou** [nhsuk/nhsuk-service-manual-community-backlog#186]
## What
> What's the best way to describe weights in NHS content eg kgs, ibs, oz,

## Why
> We want users to understand weights when we describe them

## Anything else
> For example: https://www.nhs.uk/live-well/healthy-weight/start-the-nhs-weight-loss-plan/

**Comment by sarawilcox** [comment]
Also in Jira backlog - SS-761.

**Comment by sarawilcox** [comment]
I'm closing this issue. We have some research findings about this on our issue for [Numbers, measurements, dates and time](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/321).

**Comment by sarawilcox** [comment]
The question crops up from time to time. Might be worth taking to next Style Council. 

See [GOV.UK A to Z on measurements](https://www.gov.uk/guidance/style-guide/a-to-z#measurements).

**Comment by sarawilcox** [comment]
A suggestion that to add that we should always specify the unit in ranges. E.g. 10g to 30g.

**Comment by sarawilcox** [comment]
[Comment copied over from the issue on Numbers, measurement, date and time](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/321#issuecomment-1787370427): 

More info on our logic behind showing users a 'best weight range for their height'.

- The current BMI tool shows users this weight range in the measurement they've selected, e.g. (41.6kg - 56.3kg or 6st 10lb - 9st 1lb)
- Our redesigned tool will only show users the weight measurement they’ve entered. This means we are not showing the opposite measurement in brackets as this is not considered 'useful information' in the context of when someone has already chosen their preferred measurement
- We will spell out measurement in full (kilograms/stone/pounds). Screen reader reads the abbreviations wrong (lbs as L B S). Some accessibility experts recommend not changing content especially for screen readers, as assistive tech users are usually familiar with the quirks of their software. But people who do not have English as their first language may not know what st and lbs are.
- Include the measurement after each instance of a number (41.6 kilograms and 56.3 kilograms) to keep it consistent with ‘stone/pounds’ pattern (e.g. 6 stone 10 pounds and 9 stone 1 pounds)
- Always include decimal places in kilograms the range for a kilogram is quite large and users may track the decimal place when weighing themselves
- If the imperial measurement has no ‘pounds’ value, we do not include the blank value. E.g ‘6 stone and 0 pounds’. We'll just show '6 stone'

**Comment by sarawilcox** [comment]
On the Healthy Choices Quiz we use "ml" in relation to drinks and haven't used the term "millilitres".  We had no users question what the term "ml" meant.

**Comment by sarawilcox** [comment]
The [GOV A to Z style guide](https://guidance.publishing.service.gov.uk/writing-to-gov-uk-standards/style-guides/a-to-z-style-guide/#measurements) says to spell out measurements at first mention, e.g. grams, micrograms and milligrams (but no need to spell out kg).

[Our style guide section on micrograms](https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#microgram) says to write it out in full (presumably because of the potential for confusion) but we routinely use mg without explanation. [Our section on dosage](https://service-manual.nhs.uk/content/numbers-measurements-dates-time#dosage) includes examples where we just use mg without explanation/spelling it out. Have we ever seen people getting confused about mg or are we confident it's well enough understood?

**Comment by sarawilcox** [comment]
At the July Style Council meeting, we talked about a proposal from the NHS lung health check team. They had decided to always include the unit of measurement when giving a range, e.g. 10g to 30g. 

NHS.UK medicines content does similar. For example:  
"The usual starting dose for mirtazapine is 15mg to 30mg a day. This can be increased to up to 45mg a day."

There was some discussion about which types of measurements this refers to (e.g. just grams, ml etc, or also time, or BMI). I will take this away and refine the proposal specifying which types of units it applies to and will present an updated recommendation at the next meeting.
