### ISSUE TITLE
May vs Might

### ISSUE THREAD

**Issue by SiRose** [nhsuk/nhsuk-service-manual-community-backlog#238]
## Should we be using 'may' or 'might' on NHS.UK for possibility?
I've wanted to surface this issue for some time, so here goes.

We seem to use 'may' on NHS.UK more than 'might', in contexts of possibility. I've often wondered if that's right, as 'may' feels more about permission and 'might' more about possibility.

Consider https://www.nhs.uk/medicines/ibuprofen-for-adults/ as an example: 'may' is used 12 times for possibility and 'might' only once. How can we be sure those are the right choices?

I haven't seen distinct guidance on this in the NHS Digital service manual's content style guide. Might we be confusing users in our preference for 'may'? Or indeed may we be confusing them?

## Is there a clear difference between 'may' and 'might'?

People seem to use 'may' or 'might' interchangeably, as if there's no difference between the two.

The difference has always felt pretty clear and natural to me: 'may' is about permission, 'might' is about possibility. 

"May I go to the toilet?"
_"Yes, you may."_
= Permission

"Might I go to the toilet?"
_"Well, you might."_
= Possibility

Context, like in many situations, can be vital for what feels natural.

I've looked into this further and found a bit more depth, but nothing yet that is as profoundly clear as I'd hoped.

Both https://www.englishgrammar.org/uses-of-may-and-might/ and 
https://writingexplained.org/may-vs-might-difference suggest that:

- 'may' is for permission, wish, hope, possible, factual/could be factual
- 'might' is for possibility, hypothetical, counterfactual, remotely possible, speculative

Examples using these definition still leave ambiguity for which word to use.

"Liverpool may yet win the title this season"
"Liverpool might yet win the title this season"

"Arsenal may yet win the Champions League in the next ten years."
"Arsenal might yet win the Champions League in the next ten years."

Liverpool are 25 points clear and only need 2 wins to win the title from their remaining 9 league games. But the season is suspended, with no clarity when or if it will be completed. This context is not about permission. 

It's also not about a wish or hope, unlike "May you have a glorious birthday Margaret" rather than "might you...". But it's also not entirely hypothetical or speculative. So is it 'may' or 'might'? Personally, my natural inclination is 'might'.

But where does factual morph into speculative?

Liverpool certainly should win the league, but may/might not if the season is never completed. People may/might never think Arsenal will win the Champions League -  I can(may/might) dream - but the club could qualify once in the next ten years and win it in that next season. 'Might' feels right here. Would people use 'may' here? I don't think so.

## Let's look closer

I'm curious if:

- there's a unwritten cultural convention within NHS.UK to use 'may' over 'might'
- there's an unconscious preference for one over the year
- "it's not broken so don't fix it, there's bigger priorities"
- it might be considered too big an overhead to change 'may' to 'might' where necessary
- we're using the right word
- we can agree guidance on it

I propose that we discuss the issue and agree clearer guidance on this.

## Anything else
Have we seen research evidence of:

- users' mental models around permission, possibility and hypotheticals?
- users' understanding of 'may' and 'might'?
- 'may' over 'might' being a problem for users?
- users being confused or distracted over our use of 'may' over 'might'?
- user needs being better met by matching 'may' or 'might' to the local context?

**Comment by KarinMochan** [comment]
Sorry - I clicked the wrong button!

**Comment by sarawilcox** [comment]
Hi @SiRose, sorry I never responded to this when you posted it. 

I think you're right to ask about evidence but this probably isn't an easy thing to test. My feeling is that, in the first instance, it would be good to raise it on the Slack content channel to see if anyone has seen anything in user testing that might suggest that the way we're wording things now isn't helping users. Colleagues may also have a view on how we use the two words. If you include a link to this ticket, if anyone has got any research evidence, it would be good to note it here.

PS I notice that the GOV.UK style guide doesn't address this. The Guardian style guide does (https://www.theguardian.com/guardian-observer-style-guide-m) but they're writing for a different kind of audience.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see if there is interest in us following this one up. 

@SiRose, I wonder what you think about us closing this down now? Can you think of any way we could resolve this?

**Comment by SiRose** [comment]
I suspect the outcome here lies in the issues I mentioned under "Let's look closer" - changing to 'might' would be too big an overhead. Any research evidence here would be good to see. I suspect that users regard 'may' and 'might' as interchangeable and hence largely not a problem, as long as they understand the context. Circumstances where there is confusion are probably edge cases that are hard to detect and surfaced rarely.

**Comment by sarawilcox** [comment]
Thanks @SiRose. I think I'll close this ticket but keep it in the "Not doing" column in the backlog. We can always reopen it if we find a way to test it.
