### ISSUE TITLE
Medical conditions with Nazi associations

### ISSUE THREAD

**Issue by NaoPattem** [nhsuk/nhsuk-service-manual-community-backlog#256]
There are a handful of eponyms that are linked to unethical experiments during WW2 and the holocaust. Are we doing enough to be inclusive and anti-racist when we write about these topics? 
https://en.wikipedia.org/wiki/List_of_medical_eponyms_with_Nazi_associations

There are added complications with meeting user needs. For example 'Granulomatosis with polyangiitis (Wegener's granulomatosis)' was renamed in 2011 to avoid the use of the Nazi scientists name, Wegener, however in the last three months 'Wegener's granulomatosis' is the most used search term (1135 clicks) compared to the second most searched term 'granulomatosis with polyangiitis' (652 clicks).

**Comment by sarawilcox** [comment]
Another one is Asperger's. 
Also related: terms like Mongolian blue spots.

**Comment by sarawilcox** [comment]
I've put out a call on the NHS.UK Slack content channel to see what people think about following this issue up. It hasn't come up in more recent work around inclusion.

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
