### ISSUE TITLE
NHS number and display

### ISSUE THREAD

**Issue by devansXD** [nhsuk/nhsuk-service-manual-community-backlog#283]
## What
> Briefly describe the thing you’re proposing. (It could be a style, component or pattern or something to add to the content style guide.)  

## Why
> Explain why you think we should add this to the NHS digital service manual.
>
> - What evidence do you have that services across the NHS need it?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the NHS digital service manual? 

## Anything else
- [Related issue: NHS number pattern](https://service-manual.nhs.uk/design-system/patterns/ask-users-for-their-nhs-number)
> If you can, include links to any examples, research or code to support your proposal.

**Comment by devansXD** [comment]
Placeholder for patient header data element content sessions

**Comment by sarawilcox** [comment]
Closing this issue. We think that it's covered by the NHS pattern. Unless you think we've missed something, @devansXD?
https://service-manual.nhs.uk/design-system/patterns/ask-users-for-their-nhs-number
