### ISSUE TITLE
Text-alignment 

### ISSUE THREAD

**Issue by samanthasaw** [nhsuk/nhsuk-service-manual-community-backlog#297]
## What
> Align text to the left

## Why
> Help users read text-based content

## What evidence do you have that services across the NHS need it?**

- Some users use screen magnification. Users with screen magnification at 200% may not see that text is aligned out of the screen and skip a heading
- In left to right languages, users anchor their eyes to the left after reading each sentence. This is known as reading in a F-shaped pattern. Changing this pattern will cause the user to have to make an effort to find where your sentence starts. Users could be annoyed by the change in pattern, or worse, not understand the content. 
- Advice for layout for users with dyslexia also suggests left-aligning text 
- In the context of health, users need to be able to quickly and easily read and understand content. Misunderstanding or missing content can have a considerable health impact

## Anything else

- [British Dyslexia Association guidance recommends text is left-aligned](https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide)
- [Nielsen Norman Group research on the F-shaped pattern](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/)

**Comment by sarawilcox** [comment]
This fits with some of our and GOV.UK's existing guidance, e.g.:
- left aligning the Continue button so users don't miss it: [Question pages (GOV.UK)](https://design-system.service.gov.uk/patterns/question-pages/)
- our page on [buttons](https://service-manual.nhs.uk/design-system/components/buttons)

See also [WCAG G169: Aligning text on only one side](https://www.w3.org/TR/WCAG20-TECHS/G169.html)

**Comment by sarawilcox** [comment]
Thanks @samanthasaw. Have you seen examples of services not doing this?

**Comment by samanthasaw** [comment]
Hi @sarawilcox yes we did a usability assessment today of a third party online consultation service. I noticed some of their content was center-aligned. I looked to see if there was anything in the service manual to back up left-aligning content in case we got any push back from them, as we'd recommend they left-align the text

**Comment by samanthasaw** [comment]
WCAG 1.4.8 Visual Presentation which concerns justified text:
https://www.w3.org/WAI/WCAG21/Understanding/visual-presentation.html

It doesn’t specifically mention centred text but does suggest aligning text to the left (or right):
https://www.w3.org/WAI/WCAG21/Techniques/css/C19.html

**Comment by mcheung-nhs** [comment]
And
https://www.w3.org/WAI/WCAG21/Techniques/general/G169.html

**Comment by samanthasaw** [comment]
Sorry @mcheung-nhs Sara had already added that link in a previous comment so I left it out

**Comment by mcheung-nhs** [comment]
Oops - you're right, didn't see that!

**Comment by samanthasaw** [comment]
[GOV.UK - accessible communication formats, design and layout](https://www.gov.uk/government/publications/inclusive-communication/accessible-communication-formats#design-and-layout)

**Comment by henocookie** [comment]
It's worth considering the different languages used by people using NHS services. For example, Arabic content tends to be aligned from right to left. For example, the Doctoori website, linked to from the [NHS.UK Health information in other languages page](https://www.nhs.uk/about-us/health-information-in-other-languages/) can be viewed in both English and Arabic. When Arabic is selected, the whole layout of the website changes, for example on the [common health questions page](https://www.doctoori.net/ar/health-information/common-health-questions/).

![Doctoori Ar](https://user-images.githubusercontent.com/52792328/111973852-d41a1880-8af6-11eb-9594-3c5dafc1521a.png)

![Doctoori En](https://user-images.githubusercontent.com/52792328/111973859-d5e3dc00-8af6-11eb-80ad-82d828c905c8.png)

**Comment by sarawilcox** [comment]
Yes, we should probably specify left-aligning for languages that run left to right, like English. And right-aligned for content that runs right to left, like Arabic.

**Comment by sarawilcox** [comment]
> Align text left for maximum legibility. Avoid right aligning or justifying text. 
From [GOV.UK Guidance: Accessible communication formats](https://www.gov.uk/government/publications/inclusive-communication/accessible-communication-formats)

**Comment by sarawilcox** [comment]
I think we have enough information here to take this to the next Style Council meeting.

**Comment by sarawilcox** [comment]
@karlgoldstraw suggests that we'd probably want to cover this under typography: https://service-manual.nhs.uk/design-system/styles/typograph - like a utility class, or a helper.

Also, I think we should mention it under Formatting and punctuation in the content style guide: https://service-manual.nhs.uk/content/formatting-and-punctuation

See this GOV.UK frontend issue: https://github.com/alphagov/govuk-frontend/issues/1824

**Comment by sarawilcox** [comment]
Another example of right to left is the BBC Farsi (Persian) language page: https://www.bbc.com/persian.

**Comment by sarawilcox** [comment]
I see that GOV has published new override classes for text alignment: https://github.com/alphagov/govuk-frontend/releases/tag/v3.14.0. Is this the approach we'd take?

**Comment by henocookie** [comment]
> I see that GOV has published new override classes for text alignment: https://github.com/alphagov/govuk-frontend/releases/tag/v3.14.0. Is this the approach we'd take?

Seems sensible. I guess this would be alongside guidance to align text to the left in most instances, as suggested by @samanthasaw in the initial issue?

**Comment by sarawilcox** [comment]
This is what I'm thinking of putting to the next Content Style Council meeting, early December. We could add it to the [Formatting and punctuation page in the content style guide](https://service-manual.nhs.uk/content/formatting-and-punctuation). 
![Screenshot 2021-11-01 at 11 00 42](https://user-images.githubusercontent.com/45792959/139669034-89d8e221-c1c4-45ae-8e47-58b37a4c6810.png)

@teodorastraianu1 is considering what we need to add to the design system, including a new override class for text alignment. 

@samanthasaw for info.

**Comment by sarawilcox** [comment]
@teodorastraianu1 A question. Would we need to justify if supporting 2 languages at the same time, e.g. English left to right and Arabic right to left. See this page: https://paper.dropbox.com/doc/Multiple-language-support-hSVIJqjyWFVc5N6Irvxnn

**Comment by teodorastraianu1** [comment]
@sarawilcox No, I don't think we would have to justify (unless I am missing something). 

I agree we should probably not mention mixing multiple languages in one page, especially since this is just guidance on text alignment, not on producing content in languages other than English.

**Comment by teodorastraianu1** [comment]
This is what we are thinking of adding to the Design System, to the Typography page.

<img width="762" alt="Screenshot 2021-11-05 at 16 33 38" src="https://user-images.githubusercontent.com/73899034/140545739-722aa643-2782-4446-bcf0-6f674b225997.png">

We would also add a code snippet (which @danjohnstonUX is currently working on) and an example of what right-aligned text would look like. We are thinking of using an Arabic example, since that's the use case we recommend right-aligning for. We are thinking of saying "Aligning Arabic text to the right", which would look something like this (needs to be checked by one/a few Arabic speakers to make sure it's a good translation):

![image](https://user-images.githubusercontent.com/73899034/140545378-c60e9422-b7a1-42d8-929d-f2339a7ea30e.png)

**Comment by sarawilcox** [comment]
We're proposing to add something like this to the content style guide as well, on the [Formatting and punctuation page](https://service-manual.nhs.uk/content/formatting-and-punctuation).
![Screenshot 2021-11-01 at 12 05 52](https://user-images.githubusercontent.com/45792959/140548135-3ff8b016-b41b-4afd-afb4-0627946b97a6.png)

**Comment by samanthasaw** [comment]
Looks good to me! @teodorastraianu1 @sarawilcox

**Comment by henocookie** [comment]
This will be taken to the Content Style Council and Design System Working Group tomorrow (7th December 2021) for discussion to see if there are any objections to progressing forward and publishing the guidance and [adding a utility class to nhsuk-frontend](https://github.com/nhsuk/nhsuk-frontend/issues/789)

**Comment by samanthasaw** [comment]
[Style council - left align content.pptx](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/files/7676196/Style.council.-.left.align.content.pptx)

Slides I presented at the style council on 7 December 2021

**Comment by henocookie** [comment]
At the December Design System Working Group session, left-align text was presented by @samanthasaw, @sarawilcox  and @henocookie. This was discussed and voted on by the DSWG members.

### Key points of discussion:

- Consider whether the guidance is applicable for clinical facing systems
- Alignment of components should be a new backlog item, but guidance for left-aligning text seems good to publish
- Consider where this guidance could also be surfaced in the accessibility guidance section of the service manual
- Include guidance to not use justified text unless user research shows it would be useful for a particular service

### Vote to publish:

12 - Ready to publish now
5 - Needs a little more work
0 - Needs a lot more work
0 - Not right now

### Next steps

- [ ] Re-name this issue to only focus on text-alignment, not left-alignment for other non-text content types
- [ ] Create a new issue to explore alignment guidance for other components and patterns
- [ ] Iterate the guidance based on discussion points. @sarawilcox could we work together on this please?
- [ ] @henocookie to create PR in nhsuk-frontend to add left, centre and right text-alignment utility classes

**Comment by sarawilcox** [comment]
A weird example of right aligned English and Arabic: https://www.gov.uk/government/publications/instructions-for-covid-19-self-test.ar.

**Comment by henocookie** [comment]
I've checked and it appears there is no common example of code editors allowing for right-aligned editing. For example, [Apple still uses left-to-right examples of code](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html) when showing how to adapt interfaces Internationally to support right-to-left languages.

**Comment by henocookie** [comment]
Guidance tweaks pending a content review from @sarawilcox following feedback and next steps agreed after the December 2021 DSWG session.

![Formatting-and-punctuation-NHS-digital-service-manual](https://user-images.githubusercontent.com/52792328/146207754-40ed87f7-def1-4b41-a801-9dd00b3d8e9e.png)
![Typography-NHS-digital-service-manual](https://user-images.githubusercontent.com/52792328/146207773-9ca2b057-cb16-4636-94e0-666271e31da3.png)

**Comment by henocookie** [comment]
Guidance and examples for text-alignment in the GOV.UK Design System: https://design-system.service.gov.uk/styles/typography/#text-alignment-override-classes

**Comment by sarawilcox** [comment]
Above text for content style guide approved at December Content Style Council. Notes of Style Council meeting to be approved by clinicians.

**Comment by henocookie** [comment]
To do once the [nhsuk-frotnend update](https://github.com/nhsuk/nhsuk-frontend/pull/802) is released:

- [ ] update the nhsuk-frontend version for the service manual app
- [ ] update the text-alignment example to use the nhsuk-frontend right-align text-alignment class
- [ ] remove the custom text-alignment CSS in the service manual app

**Comment by henocookie** [comment]
Custom CSS in the service manual is now removed. Just awaiting final content tweaks @sarawilcox is working on :)

**Comment by henocookie** [comment]
Closed as the guidance has now been published in [v5.7.0 of the NHS digital service manual](https://github.com/nhsuk/nhsuk-service-manual/releases/tag/v.5.7.0) 🚀
