### ISSUE TITLE
BSL video guidance

### ISSUE THREAD

**Issue by richkelly13** [nhsuk/nhsuk-service-manual-community-backlog#412]
Create guidance and best practice around how to make BSL video content. This is to go on the NHS digital service manual.

**Comment by richkelly13** [comment]
**DRAFT GUIDANCE**

British Sign Language (BSL) translation synchronises on top of any video content. Conventionally, a translator or interpreter are placed in the bottom right hand of a video.

It will serve BSL users better if the person in the videos are a 'deaf qualified translator,' rather than a 'hearing qualified interpreter'. Definitions of these can be found below:


**Deaf translator**

Sign language is not a mimicry of English it is a separate language. Therefore, it is not directly translatable as it is a unique tool of communication.

Translators read a whole script and digest it then present it in chunks but don't translate as English verbatim. They will translate the information structurally to Sign Language - taking out any unnecessary metaphors or unneeded content. It's best practice to use a Deaf person because their approach is more in-line with the end user of the product.

A Deaf translator would be useful for pre-planned videos where a script is available to translate.


**Hearing interpreter**

BSL interpreters listens and immediately translates the English verbatim to sign language, or vice-versa, watches sign-language and translates it to English. Interpretation takes place in real time, whether in-person or remotely and is part of the ongoing discourse between the Deaf and hearing parties. A hearing interpreter would be useful in a live video streaming event where there is no existing script.


**Other considerations:**

It is worth confirming with the translator whether there is a requirement of 'transliteration' of the content as there may be nuances in the script that might need transliteration (offering a graphic on screen to support the communication).

Diversity needs to be reflected in the translators/interpreters used and the delivery needs to be culturally sensitive.

Some videos are too fast for BSL users. BSL translations are often placed on top of pre-recorded video. If signing is extremely fast, then it loses all meaning. Be conscious of this at script, pre-production and production stages.

There are regional variations in BSL languages but the translator's aim is to try and standardise the variations to cater for a nationwide deaf audience - same as you get with varying accents in the UK. 

A word of warning that as a non-native in BSL you cannot relate and fully empathise - so it's important to run content past partners and charities who can help confirm good standards.


[ from a trained BSL Translator ]

**Comment by sarawilcox** [comment]
NHS.UK's additional language support project found that Deaf BSL users faced significant problems with:
- knowing what medical services are available to them 
- accessing health information
- making informed decisions about their care 
- getting information in accessible formats

Providing information in BSL has the potential to prevent clinical risk and improve people’s experiences of health, care and wellbeing.

**Comment by sarawilcox** [comment]
Closing this issue as it's been replaced by a newer, more specific issue - see above.
