### ISSUE TITLE
Summary page bug

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual-community-backlog#415]
## What is the problem?
I created a prototype where the user can select a number of checkboxes and see the answer on a summary page, but for some reason the nunjunk is producing the answer horizontally

## Bugs
It is showing checkbox answers horizontally on summary page

### What did you expect to happen?
I expect it to show the checkbox answers in one line

### Reproducing the bug

- NHSUK frontend version:
- Node version:
- npm version:

Steps to reproduce it:

1. Select checkboxes
2. Select continue
3. On summary page
4. See checkbox answers

## Attachments
<img width="1146" alt="Screenshot 2022-01-24 at 09 29 51" src="https://user-images.githubusercontent.com/71393402/150794144-5cd37977-55fb-417d-a775-45d5432689cc.png">

CSSE tool prototype link - https://cervical-screening-interim.herokuapp.com/v12/CSSE-tool/CSSE-create-step3
Username: total
Password: recall

**Comment by henocookie** [comment]
Thanks for submitting this bug @Tosin-Balogun. Is there a developer or engineer on your team that could check the code in the first instance?

If this does look like a bug that could affect other prototypes and services, do re-open the issue so we can investigate further
