### ISSUE TITLE
Appointments: how to explain how to interact with their GP surgery/how to get a GP appointment

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual-community-backlog#424]
## What

**The problem:**
The process for getting a GP appointment is changing for many GP practices. Instead of calling up to get an appointment, many practices ask patients to fill in an online form, triage the patients then allocate appointments based on urgency. 

GP practices aren’t explaining the new process well/at all.  Many patients are unaware of or confused by the new system. The means of contacting the practice (online, phone, in person) are often confused with the way the consultation takes place (phone, face to face, video)

## Why

**What we have learned**
From usability testing of GP websites and Online Consultation systems with 60 participants with mid-low digital and language confidence:
•	Patients prefer to phone up for an appointment. It’s familiar, they feel they’re guaranteed to get a result from phoning and they feel it’s the best channel to be understood. Phoning for an appointment can be challenging but it’s considered the best and often only option. 
•	GP practices don’t explain clearly what they want patients to do, in which situations and the information on their websites is often out of date and lengthy. 
•	As patients start on the GP website and then move onto the Online Consultation supplier product, this journey is fragmented and patients can get lost and end up going around in circles between different sites and systems. 
•	GP websites and specifically primary navigation often doesn’t prioritise the most used tasks for patient users. 
•	The language used around the process (Online consultation, triage etc) is inconsistent and confusing to patients. The use of the supplier names (there are many different ones) is also confusing to patients

From qualitative research conducted in Humber with mixed deprivation levels, exploring understanding of, and attitudes to, different access routes, as well as responses to different messaging. 

Evidence suggests there are 3 main barriers to address:
•	Knowledge – raise awareness as low for most (or have experience of older systems) 
•	Education – exactly what is available online and how they use it 
•	Confidence – dispel fears by offering transparency in process, give acknowledgment of request, provide clear timescale, clarity on who can see information etc. 

Stimulus can be interpreted as being about appointment types rather than ways of getting in touch as patients' mindset is focused on end result rather than the journey. Therefore, need to be crystal clear that this is about initial contact routes
There is a need to clarify this is about contacting the GP practice and not the doctor themselves – without this addition it’s reinforces default thinking about appointment types 

## Anything else

**What we are considering**
We need some NHS recommended, patient centric copy which is clear and consistent throughout the journey, across all channels. 
This can be used:
•	In GP practices to use in their comms
•	By GP website suppliers
•	By Online Consultation system suppliers in their products

We are testing new copy on 2 GP websites as part of usability testing the process of submitting your needs online:

Copy for GP websites:
There are now 3 ways to contact us:
•	Phone us at 8am, Monday to Friday on XXXXXXXXX
•	Visit the surgery during opening hours and speak with a receptionist
•	Ask for an appointment online
Book an appointment 

All appointments are over the phone, face to face or over a video call. You may be treated by a GP, a nurse or other health professional.

**Comment by sarawilcox** [comment]
### Explaining GP appointments and how to get them

The Digital First Primary Care team has some recommended copy to use on the Appointments page of a GP website.  

I suggest that we see what Style Council thinks about adding something like this to the style guide.

**Comment by sarawilcox** [comment]
Discussed draft copy about appointments at October Style Council meeting. 

At this stage, we weren’t debating the copy itself but the question about whether it should be in the service manual.  

There were only 13 votes out of 36 in favour of publishing in the style guide. No votes against. Other people weren't sure. 

Someone suggested the NHSD GP tool kit: [NHS App guidance for GP practices - NHS Digital](https://www.england.nhs.uk/publication/gp-online-services-communications-toolkit/) (App focused)  

Some other places: 
- [GP online services toolkit: Introduction (RCGP)](https://elearning.rcgp.org.uk/mod/book/view.php?id=13455) 

- [GP online services communications toolkit (NHS England)](https://www.england.nhs.uk/publication/gp-online-services-communications-toolkit/) - PDF only 

Action: I'll explore further with service manual stakeholders.

**Comment by sarawilcox** [comment]
(DRAFT copy about appointments for GP websites)[https://docs.google.com/document/d/1LDsSEEQ96ppra1SYD2w6jyVqq1JvyvVa9rEELxbtTbc/edit?usp=sharing]

**Comment by sarawilcox** [comment]
NHS England is working on a language guide for communications about general practice access routes that will include this sort of guidance. Might be worth adding some brief guidance on appointments and consultations to the style guide to align it and to link to the fuller guidance.

**Comment by sarawilcox** [comment]
What is an appointment? From the  NHS Primary Care Bulletin May 2023.

<img width="500" alt="Screenshot 2023-05-25 at 17 55 53" src="https://github.com/nhsuk/nhsuk-service-manual-community-backlog/assets/45792959/235b3d23-3932-4173-aa7c-d2bbfd9ab211">

**Comment by sarawilcox** [comment]
At the October 2022 meeting we could not decide whether to include some guidance for GP practice staff on how to word content about contacting a surgery to get an appointment. The Digital First Primary Care team has now published written content templates in their guidance on [Creating a highly usable and accessible GP website (NHS England)](https://www.england.nhs.uk/long-read/creating-a-highly-usable-and-accessible-gp-website-for-patients/#part-5-written-content-templates).

No plans to add anything to the style guide for the time being.
