### ISSUE TITLE
total liquid medications

### ISSUE THREAD

**Issue by AishaQtim** [nhsuk/nhsuk-service-manual-community-backlog#428]

**Comment by AishaQtim** [comment]
i have task for total liquid medications, so please i need help for explain how to make that, Regards.

**Comment by henocookie** [comment]
Hi @AishaQtim. Thank you for contacting the [NHS digital service manual](https://service-manual.nhs.uk/) team. We run the NHS digital service manual which helps NHS teams build consistent, usable digital services that put people first.

Unfortunately, we cannot help with your query. We've included some general information below that may help. I'm going to close this issue as it doesn't seem like it relates to the service manual.

### Medical advice
If you're worried about an urgent medical problem, call 111 or go to [NHS 111 online](https://111.nhs.uk/). If it's not urgent, please contact your GP or local pharmacist.

You can [find medical services near you](https://www.nhs.uk/service-search) through the NHS website. [The NHS website](https://www.nhs.uk/) also has information about medical conditions and treatments.

### NHS App, NHS COVID Pass or other COVID-19 services
[Find out about contacting the NHS App team](https://www.nhs.uk/contact-us/nhs-app-contact-us/) for technical support.

To get help with booking a vaccine or for problems with your vaccine record, call 119.

### Registering with a GP or finding your NHS number
To find or register with a GP, see the information about [GP services](https://www.nhs.uk/nhs-services/gps/) on the NHS website.

You can also [find your NHS number](https://www.nhs.uk/nhs-services/online-services/find-nhs-number/) there. You do not need to know your NHS number to get care.

### Hospital appointments
We cannot help with hospital appointments. If you have been referred to a specialist through the NHS e-Referral Service (e-RS), you can [book or manage your appointment](https://www.nhs.uk/nhs-services/hospitals/book-an-appointment/) online. 
You can also phone the NHS e-Referral Service appointment line on 0345 608 8888.

Or please contact your hospital directly. [Find your hospital service](https://www.nhs.uk/service-search/other-services/Hospital/LocationSearch/7).

### Health records
To ask for access to personal health records, you need to contact your GP practice, hospital or other care provider. We do not have access to personal health records.

Find out how to:

- [access your health records](https://www.nhs.uk/using-the-nhs/about-the-nhs/how-to-access-your-health-records/)
- [access someone else's health records](https://www.nhs.uk/common-health-questions/nhs-services-and-treatments/can-i-access-someone-elses-medical-records-health-records/)
 
### Help with health costs
[Find out about help with health costs](https://www.nhs.uk/nhs-services/help-with-health-costs/) on the NHS website.

[Check if you can get help with health costs](https://www.nhsbsa.nhs.uk/nhs-help-health-costs) on the NHS Business Services Authority website.

### NHS jobs 
You can search for [NHS job vacancies](https://www.jobs.nhs.uk/).

**Comment by sarawilcox** [comment]
Hi @AishaQtim, are you able to access the [NHS.UK Slack channel](https://app.slack.com/workspace-signin?redir=%2Fgantry%2Fauth%3Fapp%3Dclient%26lc%3D1647521372%26return_to%3D%252Fclient%252FTDJTLBAJK%252FCT2UL6RNJ%26teams%3DTDJTLBAJK%252CT04V6EBTR%252CT0FRZQSMB%252CTPU10NLV7%252CT010N7G9Q8K%252CT0196SVQ886)? If you join the #content channel there and ask your question, someone may be able to help.
