### ISSUE TITLE
Improve the hierarchy of H3 and H4 heading styles

### ISSUE THREAD

**Issue by BrieWhyatt** [nhsuk/nhsuk-service-manual-community-backlog#445]
### What is the problem?
Content designers and interaction designers have noticed that visually, there is little visual difference between H3 and H4 styles.
This means that although there won't be issues for those who navigate the site using a screen reader, those who do rely on sight may find it hard to distinguish between the hierarchy of the content

## Examples
![image (68)](https://user-images.githubusercontent.com/55788270/185628435-3b5dfb65-f9d1-46ae-b29c-91454f4c1510.png)
![Screenshot 2022-08-19 at 11 57 08](https://user-images.githubusercontent.com/55788270/185628443-51d3c06f-e6ce-440e-8b03-834dd384ab69.png)
.

We believe it would be useful to explore making the difference between these two heading styles more prominent, so that sighted users can successfully read the content.

**Comment by sarawilcox** [comment]
Recommendation from Brie.
![Screenshot 2023-04-20 at 16 47 04](https://user-images.githubusercontent.com/45792959/233419314-bd79d05c-dca8-4ebd-9369-d59c60585d34.png)

**Comment by sarawilcox** [comment]
Figma file exploring the issue: https://www.figma.com/file/AIFpsdNn1FmtVSNhbdG2vQ/CMS%2FNav-Team%3A-H4-experimentation-(Copy)?type=design&node-id=0%3A1&mode=design&t=m7WfsHgSwwo7OMjM-1

See Slack for some more comments on this issue: https://nhsuk.slack.com/archives/C05G1JY3WQ6/p1699443589717459?thread_ts=1697627595.270859&cid=C05G1JY3WQ6

**Comment by anandamaryon1** [comment]
Resolved with the new type scale and merged: https://github.com/nhsuk/nhsuk-frontend/pull/1019
