### ISSUE TITLE
Health professional, healthcare professional, healthcare team, multidisciplinary team etc

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#49]
We agreed at the March 2019 meeting that healthcare team was a good term but weren't sure whether users needed to know about multidisciplinary teams? (one word or with a hyphen multi-disciplinary team)

Also is health professional or healthcare professional easier for users?

I raised a Jira ticket: SS-400

**Comment by sarawilcox** [comment]
See Jira ticket SS-400.

**Comment by markasrobinson** [comment]
Research note: we heard a couple of users refer to their "multidisciplinary" during user testing for autism project on 20/03/19.

**Comment by sarawilcox** [comment]
We have a duplicate issue about health professionals and specialist teams at #80. I'm closing that one down and transferring over the following comment from that ticket.

Do we use the shorter "health professional" or the longer "healthcare professional" as a general term for clinicians? Or something else? Please have a word with Martine who raised the issue. She suggests the shorter version.

Also, we agreed at the March 2019 Style Council meeting, that 'healthcare team' was a good term but haven't agreed whether or not we would say, where appropriate, that it might be called a multi-disciplinary team or MDT. We agreed that we needed to research whether users will come across the term.

An initial internet search suggests that patients with diabetes or cancer may be seen by an MDT - and may need to understand what a multi-disciplinary team is.

Interestingly, in terms of cancer, some hospitals talk about 'specialist teams' or 'teams of specialist doctors and nurses'. Should we add that as a phrase we'd use?

Also there was a suggestion at the Style Council meeting that we should make multidisciplinary team one word, but I wonder whether the hyphen helps people who find reading hard?

We have a Jira ticket: SS-400.

**Comment by NettyKo** [comment]
I work as an editor of information for patients in cancer services and the term multidisciplinary teams (MDTs) is widely used both in consultations/conversations with patients and in written information. When used in written information, we explain who they are, i.e. a team of health professionals and experts in different areas of medicine and care. Personally I think it's important to include it in written info as patients (and their families and carers) will hear it anyway, also in the context of the MDT meetings as that's where their treatment plans are often agreed. In terms of the hyphen, we don't use it but it may help people with learning difficulties.

**Comment by sarawilcox** [comment]
That's very helpful. Thanks @NettyKo

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see if this is still an issue of interest. Can we close it?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
