### ISSUE TITLE
Palliative care or end of life care

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#50]
Raised at the March 2019 Style Council meeting by PHE team. 
Added as a task to Jira: SS-578

**Comment by NettyKo** [comment]
End of life care is different to palliative care - it's about improving quality of life at any stage of illness, not just when you're dying

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel. Is there interest in pursuing this issue or should we close it down now?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
