### ISSUE TITLE
NHS 111 online service

### ISSUE THREAD

**Issue by markasrobinson** [nhsuk/nhsuk-service-manual-community-backlog#53]
We need to be consistent with how we refer to the online 111 service.

Examples I have seen include:

- 111.nhs.uk
- 111 Online
- NHS 111 Online

Linking to 111 is likely to be something we do more and more in the future, so it would be helpful to have something in the A-Z about this.

**Comment by sarawilcox** [comment]
Thanks Mark. My guess is NHS 111 online but I'm checking with the 111 online content designers - assuming that they have already had discussions about this. See also: https://digital.nhs.uk/services/nhs-111-online.

**Comment by markasrobinson** [comment]
My understanding is that 111.nhs.uk is the correct term - that what was recommended when we worked on the 111 care card and was used in publicity campaigns. But would be good to confirm this so we can put it in A-Z to avoid confusion in the future.

**Comment by LaurenLM** [comment]
Sadly it's not as simple as that ;( 

I also think we should just use the URL everywhere as it makes it clear it's a website and distinct from the telephone service, but NHS England disagrees. 

So we use NHS 111 online (include NHS, always lower case 'o') in campaigns and for local areas to point to the service. But if we are just talking about how we refer to it on nhs.uk then I think we can say Call NHS 111 or go to 111.nhs.uk

**Comment by LaurenLM** [comment]
Sorry I realise that last bit is confusing. I meant to say on nhs.uk we can just say Call 111 or go to 111,nhs.uk - we don't need to refer to 'NHS' on an NHS website 😄

**Comment by sarawilcox** [comment]
Thanks, I'll put something together for the April Style Council meeting.

**Comment by markasrobinson** [comment]
On the NHS website and in national digital services, say 'Go to 111.nhs.uk or call 111' if it's a call to action. You do not need to tell people on a digital service that it's online.

In content that explains the service, use 'NHS 111 online'. Include the word NHS and give online a small 'o'.

@sarawilcox , I have confirmed the above with @LaurenLM .

We might need to consider adding something about not directing to the online service if the advice is only for young children, though. 111 online doesn't deal with children under 5.

**Comment by markasrobinson** [comment]
Suggest following addition:

"NHS 111 online is not for children under 5. Do not direct users to 111.nhs.uk if a call to action relates to young children only."

**Comment by sarawilcox** [comment]
Wording agreed at 5 June Style Council meeting: 

On the NHS website and in national digital services, say "Go to 111.nhs.uk or call 111" if it's a call to action.  

In content that explains the service, for example policy or programme content, use "NHS 111 online". Include the word NHS and give online a small "o". 

NHS 111 online is not for children under 5. Do not direct users to 111.nhs.uk if the call to action is only about young children.

**Comment by sarawilcox** [comment]
Published in the A to Z of NHS health writing.

**Comment by sarawilcox** [comment]
A couple of things have come up recently.

### How we explain that 111 online is only for over 5s

Here are 2 examples:

> Go to [111.nhs.uk](http://111.nhs.uk/) (for adults and children aged 5 and over) or call 111.

> Go to [111.nhs.uk](http://111.nhs.uk/) (for adults and children aged 5 and over) or call 111 if ...

### Moving away from using the URL

We are increasingly saying "111 online" rather than giving the URL. It's easier to read and now widely used.

**Comment by sarawilcox** [comment]
If approved, we need to change the non-clickable card in the design system too.

**Comment by sarawilcox** [comment]
Published in latest release: https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#NHS-111-online

**Comment by sarawilcox** [comment]
In a care card headed "Contact NHS 111", we just put 111 online in the link.
