### ISSUE TITLE
Foot specialist, chiropodist, podiatrist 

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#65]
At the January content Style Council meeting, we discussed the term "foot specialist" but people were concerned that a foot specialist could be a consultant or a podiatrist or chiropodist.

Also the term chiropodist is on its way out but our clinical advisor suggested we continue to use it for the time being. We agreed that someone should research this and come back with a proposal.

See Jira SS-530.

**Comment by sarawilcox** [comment]
Feedback from a member of the public responding to the BBC R4 programme on NHS language use: "the
most confusing, for patients (or "service users") was the change from
"chiropody" to "podiatry" for the clinics dealing with feet.  People who
had been seeing a "chiropodist" for years suddenly had to find the
"podiatrist"."

**Comment by sarawilcox** [comment]
The NHS.UK page on foot problems and the podiatrist: https://www.nhs.uk/live-well/healthy-body/foot-problems-and-the-podiatrist/

**Comment by sarawilcox** [comment]
There's the College of Podiatry.
And the British Chiropody and Podiatry Association.

Interestingly the [BCPA's info on athlete's foot](https://bcha-uk.org/foot-care-advice/f/athlete%E2%80%99s-foot)) talks about "podiatrists or foot health professionals". 
The info from the College of Podiatry, for example their [patient info on aging feet](https://cop.org.uk/common-foot-problems/ageing-feet) talks about seeing a podiatrist.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see if this is still an issue of interest. Can we close it?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
