### ISSUE TITLE
Contagious, infectious, catching

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#66]
There is a Jira ticket for this: SS-503.

**Comment by sarawilcox** [comment]
I've asked in the NHS.UK Slack content channel for an insight around these words and whether there is live interest in this issue.

**Comment by sarawilcox** [comment]
No interest shown in NHS.UK or public Slack channels. I'm closing this issue and the ticket in Jira.
