### ISSUE TITLE
Abortion or termination

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#69]
It will help content designers if we can clarify whether we use "abortion" or "termination". Or do we talk about "ending a pregnancy"? (In a meeting on 4 December, content designers thought we shouldn't use "termination" except perhaps to explain that an abortion is sometimes called a termination.)

Please talk to the 111 team, as they raised this as an issue.

There is a Jira ticket for this: SS-394.

**Comment by sarawilcox** [comment]
@SusieWd, it would be good to review any user research we have and how we use these words. Are you OK with me assigning it to you? No urgency. You'll see above there is a ticket in Jira for this too.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see how much interest there is in us pursuing this issue now.

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
