### ISSUE TITLE
Abnormal, abnormality, disorder 

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#70]
It will help content designers if we can clarify whether we use "abnormal", "abnormality" and "disorder" and if so, in which contexts. Otherwise, what are our preferred alternatives?

Compare with "condition" and consider autism and neurodiversity. (See #81) 

We have a Jira ticket for this: SS-393.

**Comment by annasutton2** [comment]
The PHE screening team have advised us that they are moving away from using the terms "anomaly" and "abnormality" in their information leaflets about the second pregnancy scan (20-week scan, previously called "the anomaly scan"). They have found these words didn't test well in focus groups.

**Comment by marklegassick** [comment]
I think also worth adding 'birth defect' to this ticket as we use it in a page I've recently reviewed:

https://www.nhs.uk/conditions/oesophageal-atresia/

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack #content channel to see how much interest there is in this issue now.

**Comment by sarawilcox** [comment]
No interest in this issue on NHS.UK or service manual public Slack channels. I'm closing it.

**Comment by sarawilcox** [comment]
What about "abnormal" in the context of blood test results?

Tools team use the following categories for blood pressure results:
- Low
- Healthy
- Slightly raised
- High
- Very high

**Comment by sarawilcox** [comment]
Note: we prefer not to use "normally". https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#normally
