### ISSUE TITLE
Heartbeat, heart rhythm, palpitations

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#73]
The 111 team have asked if we can discuss our use of "palpitations". They say: "We get people searching for this a lot and also 'fluttering' 'heart pounding' 'heart beating too slow' 'missing heartbeats' so the current definition is too narrow."

We need to check in with the medicines team too.

There is a Jira ticket: SS-605.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see if this is still an issue of interest. Can we close it?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
