### ISSUE TITLE
Autism - content for autistic people

### ISSUE THREAD

**Issue by markasrobinson** [nhsuk/nhsuk-service-manual-community-backlog#81]
Terminology around autism can be a sensitive subject for autistic people.

We need to produce some guidelines on what terms to use/avoid.

For example:
- autism vs autism spectrum disorder (ASD) 
- autistic person vs person with autism
- "challenging behaviour"
- signs vs symptoms

**Comment by sarawilcox** [comment]
Sounds good @markasrobinson. Is there learning from the autism project that we can build on? Would you be able to write something up or is it something we're not ready to do yet?

**Comment by markasrobinson** [comment]
I should be able to do something when we've finished the autism work - so hopefully in the next few weeks.

**Comment by sarawilcox** [comment]
Brill, thanks. I'll move it in the To Do list.

**Comment by sarawilcox** [comment]
Hi Mark, you might like to take a look at #70 too.

**Comment by Tosin-Balogun** [comment]
This was **ranked 5th**  from the `proposed` group at the content backlog prioritisation workshop held on 24-Nov-2020

**Comment by sarawilcox** [comment]
Some content design recommendations from NHS Test and Trace cognitive diversity user research:

> - providing a range of information formats (text, video, audio, easy read etc.)
> - ensuring plain English is used
> - breaking text into small chunks and using clear headings
> - jargon is defined clearly if it must be used
> - accompanying text with images to help convey meaning
> - setting expectations of the full user journey and what is expected of participants when (picture guides/social stories, and videos) can be really helpful for this
> - avoiding vague or subjective language
> - as much as possible only showing information that is relevant to the user to reduce cognitive overload

**Comment by sarawilcox** [comment]
The DHSC team working on cognitive diversity user research said that their charity partners preferred the term "autistic people" to "people with autism".

**Comment by EllenDoyle** [comment]
Is this the same or similar to #334

**Comment by sarawilcox** [comment]
> Is this the same or similar to #334?

At one point, we were writing specifically about and for people with autism. Question is, are the needs of people with autism sufficiently different to those of people with other cognitive differences to warrant specific guidance on this?

If not, we could copy the details over from this issue to the broader "cognitive diversity" issue and close this one down.

@markasrobinson or @Jean-Elg, do you have a view? Would you have time to draft anything on this topic for Style Council to consider?

**Comment by EllenDoyle** [comment]
Merged into #334 and this ticket closed.

**Comment by sarawilcox** [comment]
Moved to the "Not doing" column now that it's covered in the cognitive differences issue.
